name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 14
        uses: actions/setup-java@v3

        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
  test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Run tests
              run: ./run-tests.sh
            - name: Upload test results to Datadog
              if: always()
              run: datadog-ci junit upload --service service_name ./junit.xml

